### ISSUE TITLE
Mapzen Android SDK vs Tangram Android SDK

### ISSUE THREAD

**Issue by hallahan** [mapzen/android#134]
Hi Mapzen!

Right now I'm reading through Tangram ES, the Tangram Android SDK, and the Mapzen Android SDK. I'm noticing a bit of an overlap between the Tangram and Mapzen SDKs. For example, There are Polygon classes that are different but seem to have the same role in both:

https://github.com/mapzen/android/blob/master/library/src/main/java/com/mapzen/android/model/Polygon.java

and

https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/geometry/Polygon.java

Could you explain the reason behind this overlap and the overall relationship between these two SDKs? I understand that the Mapzen Android SDK is a wrapper for the Android bit of Tangram ES (the Tangram Android SDK), but I'm not fully clear on the specific intentions of that relationship.

When should I use the straight-up Tangram Android SDK, and when should I use the Mapzen Android SDK?

Cheers,
Nick

**Comment by sarahlensing** [comment]
Hi Nick!

The Mapzen Android SDK is where you can find all things Android by Mapzen. So, there is the Tangram project but also LOST and on-the-road, two other open source projects we wrote. The Mapzen Android SDK unifies these projects and provides convenience methods for doing actions such as setting api keys (see the documentation here: https://github.com/mapzen/android/blob/master/docs/getting-started.md or use MapView directly), map styles, and map overlay elements.

The Mapzen Android SDK provides access to the underlying Tangram MapController so you can use its advanced APIs directly (see https://mapzen.com/documentation/tangram/android-walkthrough/ and https://mapzen.com/documentation/tangram/Scene-file/) or, if you only need Tangram, you can use its Android SDK instead of the Mapzen Android SDK.

**Comment by hallahan** [comment]
Thanks Sarah, makes sense!
