### ISSUE TITLE
Investigate Android tile caching options

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#328]
* Verify load from cache
* Configure cache size
* Configurable cache size
* Override TTL sent by server

**Comment by sarahlensing** [comment]
[Once](https://github.com/tangrams/tangram-es/issues/1542) we have access to the `OkClient`, we will have the ability to override TTL sent by server with something like:
```
okClient = okClient.newBuilder().addNetworkInterceptor(new Interceptor() {
        @Override public Response intercept(Chain chain) throws IOException {
          Response originalResponse = chain.proceed(chain.request());
          return originalResponse.newBuilder()
              .header("Cache-Control", "max-age=31536000")
              .build();
        }
      }).build();
```

We will also be able to access the cache and [evict individual requests](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Cache.html#urls--)

Currently we have the ability to configure the cache size and I've verified Tangram is properly loading cached responses. 

One feature missing is the ability to receive the set of urls that will be loaded for the current map position/zoom. We will need this so that we can properly fetch tiles for areas a user wishes to cache.

cc'ing / @msmollin @matteblair for comments on anything I'm missing

**Comment by sarahlensing** [comment]
The requirements of this ticket have been satisfied. Further discussion is needed to determine requirements of the Android SDK. Conversation to be continued in downstream Tangram ticket https://github.com/tangrams/tangram-es/issues/931
