### ISSUE TITLE
Black Screen Map

### ISSUE THREAD

**Issue by luis901101** [mapzen/android#359]
I get a black screen instead of the map when I open any of the samples activities. I check internet connection, I have checked the logs many times but I have not found anything related to this problem everything seems to work fine.
On the other hand when I use 'com.mapzen:mapzen-android-sdk:1.3.2' lib from maven it works just fine, no black screen is shown, but what I want is to use BitmapMarkers on my Project and there is no BitmapMarkers on version 1.3.2 from maven, there is only here in the GitHub Project.

Screenshots:
BasicMap Activity Sample
![screenshot_20170503-135754](https://cloud.githubusercontent.com/assets/28322469/25674460/e26628e0-3008-11e7-96f1-2d5450536e05.png)

Router Activity Sample
![screenshot_20170503-135809](https://cloud.githubusercontent.com/assets/28322469/25674494/f74c3a06-3008-11e7-84ce-8af82774f42d.png)

Same activities but from a custom project that I created to test with compile 'com.mapzen:mapzen-android-sdk:1.3.2'
![screenshot_20170503-135925](https://cloud.githubusercontent.com/assets/28322469/25674527/21f5fe72-3009-11e7-8c86-a3607a34659e.png)

![screenshot_20170503-135934](https://cloud.githubusercontent.com/assets/28322469/25674535/280833a2-3009-11e7-9c3f-37bb871a2122.png)

**Comment by matteblair** [comment]
Hi @luis901101, can you tell us what device and Android version is producing this issue? Are you able to reproduce this on multiple devices?

**Comment by luis901101** [comment]
I have tested on HTC one m8 running Cyanogen 14.1 (Android 7.1.1) and I have tested on emulator versions 6.0.1 and 7.1.1.
And the only things I changed to the project in order to compile was the gradle classpath to classpath 'com.android.tools.build:gradle:2.3.0', and I also had to comment this on core build.gradle

task submodules {
//  def folder = new File( 'core/src/main/assets/styles/walkabout-style-more-labels/walkabout-style-more-labels.yaml' )
//  if(!folder.exists()) {
//    throw new GradleException("Submodules aren't present, please run:\ngit submodule init, " +
//        "\ngit submodule update\nfrom your root directory")

//  }
}

**Comment by ecgreb** [comment]
This check exists for a reason. If you don't init the submodules the map
will not be displayed in the demo app.

On May 3, 2017 5:51 PM, "luis901101" <notifications@github.com> wrote:

I have tested on HTC one m8 running Cyanogen 14.1 (Android 7.1.1) and I
have tested on emulator versions 6.0.1 and 7.1.1.
And the only things I changed to the project in order to compile was the
gradle classpath to classpath 'com.android.tools.build:gradle:2.3.0', and I
also had to comment this on core build.gradle

task submodules {
// def folder = new File( 'core/src/main/assets/styles/
walkabout-style-more-labels/walkabout-style-more-labels.yaml' )
// if(!folder.exists()) {
// throw new GradleException("Submodules aren't present, please run:\ngit
submodule init, " +
// "\ngit submodule update\nfrom your root directory")

// }
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapzen/android/issues/359#issuecomment-299046182>, or mute
the thread

**Comment by luis901101** [comment]
Hmmm my bad... Already fixed. 

Thanks  @ecgreb 
Now will be interesting if the Mapzen implements the Smart Marker Zoom you mention in #250 It's really important to Fit the Bounds to a level zoom in which every marker appears on the visible region of the map.
Thanks again.
