### ISSUE TITLE
No map rendering on Android 4 Kitkat

### ISSUE THREAD

**Issue by giaotuancse** [mapzen/android#360]
### Description
There's no map rendering on android 4 (Kitkat). 
Same with this issue https://github.com/mapzen/android/issues/115

### Mapzen SDK & Android Version
Mapzen SDK  - 1.3.3-SNAPSHOT
Tangram version 0.5.1

**Comment by matteblair** [comment]
Hi @giaotuancse, thanks for the report! Can you help us out with a few more pieces of information?
 - What is the name/model of the device that produced this issue?
 - Can you reproduce this issue on multiple devices?
 - What is the log output from the application when this problem occurs? (i.e. using `logcat`)

**Comment by giaotuancse** [comment]
Hi @matteblair, 
It's happens on all my android 4 devices (Asus zenphone 4 - Android 4.4.2 / Samsung Note 2 - Android 4.4.3).
Here's the logs i can get. Hope it helps:
![screenshot_1](https://cloud.githubusercontent.com/assets/8244528/25687967/deadec14-30a4-11e7-9061-bedb843dab4c.png)

**Comment by Smilefounder** [comment]
Hi @matteblair , any solution to fix this issue yet?

**Comment by hjanetzek** [comment]
@matteblair this is probably the Android SSL protocol issue.

@Smilefounder, @giaotuancse please try with changing https to http for the tile url in the scene file.

**Comment by giaotuancse** [comment]
@hjanetzek Can you show me where is the scene file?

**Comment by hjanetzek** [comment]
@giaotuancse if you build the android-sdk yourself you can look for https://tile.mapzen.com in core/src/main/assets/styles/bubble-wrap/bubble-wrap-style-more-labels.yaml. Otherwise you could add your own scene file and load it like this:

```
MapFragment mapFragment = (MapFragment) getSupportFragmentManager().findFragmentById(R.id.map_fragment);
mapFragment.getMapAsync(new MapStyle("path_to_your_scene_asset.yaml"), new OnMapReadyCallback() {
  @Override public void onMapReady(MapzenMap map) {
    // Map is ready.
  }
});
```
https://github.com/mapzen/android/blob/master/docs/getting-started.md

**Comment by hjanetzek** [comment]
So the issue is that our SSL provider deprecated TLS 1.0 [1] and pre-Lollipop Android versions don't have TLS 1.2 enabled by default. The common solution when using okhttp seems to be this snippet https://github.com/square/okhttp/issues/2372#issuecomment-244807676

[1] https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan
